version: '3.8'
services:
db:
image: postgres:15
restart: always
environment:
POSTGRES_USER: postgres
POSTGRES_PASSWORD: postgres
POSTGRES_DB: ai_resume
volumes:
- dbdata:/var/lib/postgresql/data
ports:
- "5432"